obstacle_range: 1.5
raytrace_range: 2.0
footprint: [[0.26, 0.18], [0.26, 0.014], [0.31, 0.014], [0.31, -0.014], [0.26, -0.014], [0.26, -0.18], [-0.27, -0.18], [-0.27, 0.18]]
inflation_radius: 0.25

TrajectoryPlannerROS:
    acc_lim_x: 0.25
    acc_lim_y: 0.25
    acc_lim_th: 0.6
    max_vel_x: 0.05
    min_vel_x: 0.01
    max_rotational_vel: 0.1
    min_in_place_rotational_vel: 0.05
    escape_vel: -0.05
    holonomic_robot: true
    meter_scoring: true

hokuyo_laser: 
    sensor_frame: base_laser_front_link
    data_type: LaserScan
    topic: base_scan
    expected_update_rate: 1.0
    marking: true
    clearing: true
    obstacle_range: 3.0

observation_sources: hokuyo_laser
