TrajectoryPlannerROS:
    acc_lim_x: 0.25
    acc_lim_y: 0.25
    acc_lim_th: 0.6
    max_vel_x: 0.05
    min_vel_x: -0.05
    max_rotational_vel: 0.1
    min_in_place_rotational_vel: 0.01
    escape_vel: -0.05
    holonomic_robot: true
    meter_scoring: true
