global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  plugins:
    - name: footprint_layer
      type: "costmap_2d::FootprintLayer" 
    - name: obstacle_layer
      type: "costmap_2d::ObstacleLayer" 
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"